# see example config here: https://github.com/adityatelange/hugo-PaperMod/blob/7e5d17f08ac68ef7a365ba63d2f34a8c9f3a962a/config.yml

baseURL: https://withian.net/
languageCode: en-us
title: ğŸ“– Adventures with Ian
theme: [hugo-video, PaperMod]

pagination:
  disableAliases: false
  pagerSize: 15
  path: page

enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true

enableGitInfo: true

buildDrafts: false
buildFuture: true # Allow posts with future dates
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  # https://gohugo.io/getting-started/configuration-markup/#goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

  # https://gohugo.io/getting-started/configuration-markup/#highlight
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: github-dark
    tabWidth: 4

params:
  env: production
  author: Ian Caragol
  defaultTheme: auto

  homeInfoParams:
    Title: Adventures with Ian
    Content: >
      #### (and Paddington)

      ---

      #### This is a place to share my journey across Japan and China as well as random thoughts.

      ---

      ğŸ“– To read a post below, simply click anywhere on the cover image or it's description


      ğŸ“‚ See Categories to filter by area (Japan, Bikepacking, etc...)

  cover:
    linkFullImages: false # don't make cover images clickable. Leads to bad UX

  keywords:
    - journal
    - web posts
    - memories
    - adventure
    - travel
    - writing

  # ---- opengraph ----
  title: With Ian
  description: journal / blog / web posts
  images:
    - default.png
  # ------- end -------

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowBreadCrumbs: true
  ShowToc: true # table of contents on blog posts
  comments: false
  # images: ["papermod-cover.png"]

  socialIcons:
    - name: github
      url: "https://github.com/IanCaragol"
    - name: strava
      url: "https://www.strava.com/athletes/21527643"

  # editPost:
  #   URL: "https://github.com/iancaragol/with/tree/main/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Gallery ğŸ“·
      url: gallery
      weight: 3
    - name: Search ğŸ”
      url: search
      weight: 5
    - name: Archive ğŸ“š
      url: archives
      weight: 10
    - name: Tags ğŸ·ï¸
      url: tags
      weight: 15
    - name: Categories ğŸ“‚
      url: categories
      weight: 20
